import React from "react";
import type { Metadata } from "next";
import { Syne,Inter } from "next/font/google";


import "./styles.css";

const syce = Syne({ subsets: ["latin"],display: 'swap',variable: '--font-syne', });
export const inter = Inter({ subsets: ["latin"],variable: '--font-inter', });
export const metadata: Metadata = {
  title: "blogr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <html lang='en'>
        <body className={`${syce.className} bg-dark-1`}>

          <div className="min-h-screen min-w-screen">
            {children}
          </div></body>
      </html>

  );
}
